### ISSUE TITLE
NullPointerException While using this Lib in Android Application

### ISSUE THREAD

**Issue by aarani** [badoualy/kotlogram#18]
Hey . 
tnx for your great project. i get
`06-16 02:24:39.884 897-897/ir.aarani.memberbegir E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: ir.aarani.memberbegir, PID: 897
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.aarani.memberbegir/ir.aarani.memberbegir.MainActivity}: kotlin.KotlinNullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
at android.app.ActivityThread.access$1100(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                    Caused by: kotlin.KotlinNullPointerException
at com.github.badoualy.telegram.mtproto.auth.AuthKeyCreation.createAuthKeyInternal(Unknown)
at com.github.badoualy.telegram.mtproto.auth.AuthKeyCreation.createAuthKey(Unknown)
at com.github.badoualy.telegram.api.DefaultTelegramClient.generateAuthKey(Unknown)
at com.github.badoualy.telegram.api.DefaultTelegramClient.init(Unknown)
at com.github.badoualy.telegram.api.DefaultTelegramClient.<init>(Unknown)
at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Unknown)
at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient$default(Unknown)
at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Unknown)
at ir.aarani.memberbegir.MainActivity.onCreate(MainActivity.java:51)
at android.app.Activity.performCreate(Activity.java:6876)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:158) 
at android.app.ActivityThread.main(ActivityThread.java:7224) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
`
error while running sample code that you use

**Comment by badoualy** [comment]
Hi,

I'll investigate when I have some time, but I have to warn you that Kotlogram was not intended to be used with Android as it does not address issues such at connectivity (no internet, 
disconnection, etc) and will probably work very poorly if running on an Android device.

If you want to develop an Android client, I suggest you take a look to Telegram's Android library
https://core.telegram.org/tdlib

Regards.

**Comment by aarani** [comment]
Tnx So Much :+1:
