### ISSUE TITLE
RejectedExecutionException on Android

### ISSUE THREAD

**Issue by xanscale** [badoualy/kotlogram#26]
Second time i create a thread to make a call i receive RejectedExecutionException. i think there is someting wrong with rxJava thread management.

if all method are synchronous why you use rxJava? which implementation you suggest to make calls in background?

they crash on authSignIn (called after authSendCode) 

```
public class TelegramLoginFragment extends AbstractFragment {
	@BindView(R.id.phone) EditText phone;
	@BindView(R.id.code) EditText code;
	private TelegramClient client;
	private TLSentCode sentCode;

	@Nullable @Override public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
		View v = inflater.inflate(R.layout.fragment_telegram_login, container, false);
		ButterKnife.bind(this, v);
		return v;
	}

	@OnClick(R.id.authSendCode) void authSendCode() {
		new AsyncTask<String, Void, Void>() {
			@Override protected Void doInBackground(String... params) {
				client = Kotlogram.getDefaultClient(((Application) getActivity().getApplication()).getTelegramApp(), (TelegramApiStorage) getActivity().getApplication());
				try {
					sentCode = client.authSendCode(false, params[0], true);
				} catch (Exception e) {
					e.printStackTrace();
				} finally {
					client.close();
				}
				return null;
			}
		}.execute(phone.getText().toString());
	}

	@OnClick(R.id.authSignIn) void authSignIn() {
		new AsyncTask<String, Void, Void>() {
			@Override protected Void doInBackground(String... params) {
				try {
					TLAuthorization authorization = client.authSignIn(params[0], sentCode.getPhoneCodeHash(), params[1]);
					TLUser self = authorization.getUser().getAsUser();
					System.out.println("You are now signed in as " + self.getFirstName() + " " + self.getLastName() + " @" + self.getUsername());
				} catch (Exception e) {
					e.printStackTrace();
				} finally {
					client.close();
				}
				return null;
			}
		}.execute(phone.getText().toString(), code.getText().toString());
	}
}
```

```
W/System.err: java.util.concurrent.RejectedExecutionException: Task com.github.badoualy.telegram.mtproto.MTProtoWatchdog@b989c25 rejected from java.util.concurrent.ThreadPoolExecutor@92bf1fa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
W/System.err:     at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:620)
W/System.err:     at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$start$1.call(MTProtoWatchdog.kt:120)
W/System.err:     at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$start$1.call(MTProtoWatchdog.kt:111)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10151)
W/System.err:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
W/System.err:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10151)
W/System.err:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
W/System.err:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
W/System.err:     at rx.Observable.subscribe(Observable.java:10247)
W/System.err:     at rx.Observable.subscribe(Observable.java:10214)
W/System.err:     at rx.Observable.subscribe(Observable.java:9989)
W/System.err:     at com.github.badoualy.telegram.mtproto.MTProtoHandler.startWatchdog(MTProtoHandler.kt:91)
W/System.err:     at com.github.badoualy.telegram.mtproto.MTProtoHandler.resetConnection(MTProtoHandler.kt:106)
W/System.err:     at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:253)
W/System.err:     at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:215)
W/System.err:     at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:193)
W/System.err:     at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.executeRpcQuery(TelegramClient.kt:57)
W/System.err:     at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQuery(DefaultTelegramClient.kt:189)
W/System.err:     at com.github.badoualy.telegram.tl.api.TelegramApiWrapper.authSignIn(TelegramApiWrapper.java:301)
W/System.err:     at com.zerounotribe.numina.dashboard.fragment.telegram.TelegramLoginFragment$2.doInBackground(TelegramLoginFragment.java:57)
W/System.err:     at com.zerounotribe.numina.dashboard.fragment.telegram.TelegramLoginFragment$2.doInBackground(TelegramLoginFragment.java:54)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)

```

**Comment by J-rooft** [comment]
I receive this kind of error when I call `client.close()` after each call. The solution for me was to keep the connection and do not close it.

**Comment by xanscale** [comment]
yes works thz

**Comment by badoualy** [comment]
Yup, closing the client after each call is not a good idea, you'll add an unnecessary overhead each time by having to open a new connection, with some methods being executed (such as `initConnection`).
By the way, as mentioned in the documentation, if you want to close the client, but you are expecting to open another one later, use `client.close(false)` instead, it'll also solve your bug. 

By default, closing the connection without the `false` flag will cleanup some threads used by the lib (a Timer, a ThreadPool, ...). This is why you get your error, you'll try to add new runnable to a shutdown threadpool.
