### ISSUE TITLE
Exception generating AuthKey

### ISSUE THREAD

**Issue by luzzif** [badoualy/kotlogram#29]
Kotlogram throws an exception trying to generate the authorization key. It could also help the fact that before the final, fatal exception, Kotlogram throws 4-5 other exceptions, with a "Connection reset by peer" error message (I think it might be because Kotlogram tries to connect to the default data centers, but fails).

Here you get the stack trace:
```
[java.lang.RuntimeException: Couldn't generate authorization key
	at com.github.badoualy.telegram.api.DefaultTelegramClient.generateAuthKey(DefaultTelegramClient.kt:111) ~[api-21cccea784273c5d45a3bb0de872a2b9ef5b2dad.jar:na]
	at com.github.badoualy.telegram.api.DefaultTelegramClient.init(DefaultTelegramClient.kt:77) ~[api-21cccea784273c5d45a3bb0de872a2b9ef5b2dad.jar:na]
	at com.github.badoualy.telegram.api.DefaultTelegramClient.<init>(DefaultTelegramClient.kt:70) ~[api-21cccea784273c5d45a3bb0de872a2b9ef5b2dad.jar:na]
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt:30) ~[api-21cccea784273c5d45a3bb0de872a2b9ef5b2dad.jar:na]
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient$default(Kotlogram.kt:29) ~[api-21cccea784273c5d45a3bb0de872a2b9ef5b2dad.jar:na]
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt) ~[api-21cccea784273c5d45a3bb0de872a2b9ef5b2dad.jar:na]
	at com.github.luzzif.telegram.TelegramTask.authenticate(TelegramTask.java:57) ~[main/:na]
	at com.github.luzzif.telegram.TelegramTask.execute(TelegramTask.java:40) ~[main/:na]
	at com.github.luzzif.telegram.TelegramTaskExecutor.startDaemon(TelegramTaskExecutor.java:16) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 18 common frames omitted](url)
```

**Comment by badoualy** [comment]
You'll get this exception when `generateAuthKey` returns null, you can check at https://github.com/badoualy/kotlogram/blob/master/mtproto/src/main/kotlin/com/github/badoualy/telegram/mtproto/auth/AuthKeyCreation.kt#L66

Can't say anything without more logs

**Comment by luzzif** [comment]
Diving a bit deeper into the code, the single instruction causing the problem is `val read = socketChannel.read( buffer )` (from the method `readBytes` into the `MTProtoTcpConnection` class). Tell me if you need more infos about it.

**Comment by badoualy** [comment]
Then you have a network issue, but I have no clue as why 😢

**Comment by luzzif** [comment]
Could it be because I'm under VPN?

**Comment by badoualy** [comment]
Maybe, not sure what effect it could have on Telegram's end

**Comment by luzzif** [comment]
I'll retry as soon as I have access to a non-VPN network and I'll keep you updated.

**Comment by luzzif** [comment]
Tried again on a non-VPN network. Authorization key generation went on without any problem. Closing.
