### ISSUE TITLE
Can not dowlnload file/photo

### ISSUE THREAD

**Issue by vishnyakov-aleks** [badoualy/kotlogram#30]
```java
@Override
    public void onUpdates(TelegramClient telegramClient, TLUpdates tlUpdates) {
        for (TLAbsUpdate update : tlUpdates.getUpdates()) {
            if (!(update instanceof TLUpdateNewMessage)) {
                continue;
            }
           TLAbsMessage absMessage = ((TLUpdateNewMessage) update).getMessage();
            if (!(absMessage instanceof TLMessage)) {
                continue;
            }
            TLMessage message = (TLMessage) absMessage;
            message.getMessage(); // MESSAGE BODY
            if (message.getMedia() != null) {
                TLAbsMessageMedia media = message.getMedia();
                // Magic utils method from api module
                MediaInput mediaInput = TLMediaUtilsKt.getAbsMediaInput(media);
                if (mediaInput != null) {
                    String filename;
                    if (media instanceof TLMessageMediaPhoto || media instanceof TLMessageMediaWebPage) {
                        filename = "photo.jpg";
                    } else {
                        // Retrieve real name
                        TLDocument tlDocument = ((TLMessageMediaDocument) media).getDocument().getAsDocument();
                        filename = ((TLDocumentAttributeFilename) tlDocument.getAttributes().stream()
                                .filter(attr -> attr instanceof TLDocumentAttributeFilename)
                                .findFirst().get()).getFileName();
                    }
                    try {
                        FileOutputStream fos = new FileOutputStream(new File(Main.ROOT_DIR, filename));
                        telegramClient.downloadSync(mediaInput.getInputFileLocation(), mediaInput.getSize(), fos);
                        System.out.println(new File(Main.ROOT_DIR, filename).length());
                    } catch (IOException | RpcErrorException e1) {
                        e1.printStackTrace();
                    }
                } else {
                    System.err.println("MessageMedia type not supported" + media.getClass().getSimpleName());
                }
            }
        }
    }

```
when message has file - i receive Exception
```
[UpdatePool-thread-2] ERROR com.github.badoualy.telegram.api.TelegramClient - Unhandled RpcError 400: LIMIT_INVALID
[RxComputationScheduler-1] ERROR com.github.badoualy.telegram.mtproto.MTProtoHandler - rpcError 400: LIMIT_INVALID
400: LIMIT_INVALID
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:245)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:215)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:193)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:199)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.downloadSync(DefaultTelegramClient.kt:280)
	at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.downloadSync(TelegramClient.kt:151)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.downloadSync(DefaultTelegramClient.kt:32)
	at MApiCallback.onUpdates(MApiCallback.java:63)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.onUpdates(DefaultTelegramClient.kt:388)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler$handleMessage$1.run(MTProtoHandler.kt:491)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

What am i doing wrong?

**Comment by badoualy** [comment]
Seems to be an issue with the lib, I'll check as soon as I have some free time with some media.
What kind of media were you trying to download?

**Comment by vishnyakov-aleks** [comment]
It was anything file, and picture
Size was from 800 bytes to 7 mBytes

**Comment by vishnyakov-aleks** [comment]
I could not sit on the spot

error while you are send to telegram limit, that cannot divide (sorry for my eng) by 1024!

i was replace line 273 of DefaultTelegramClient.kt
`                methods.add(TLRequestUploadGetFile(inputLocation.inputFileLocation, offset, 524288))
`instead
`                methods.add(TLRequestUploadGetFile(inputLocation.inputFileLocation, offset, limit))
`
And it works great. 
Thanks for your library, thank you for your work;)

**Comment by vishnyakov-aleks** [comment]
i am waiting for this (or another) fix in next release ;)

**Comment by badoualy** [comment]
Fixed in next commit, in a few minutes/hours.

FYI: before, sending a limit not dividable by 1024 was totally ok, seems to have changed, now downloading only by parts of 128*1024 bytes.

It's tested, and I updated to sample to reflect the changes :)
