### ISSUE TITLE
IOException Reached end-of-stream

### ISSUE THREAD

**Issue by xanscale** [badoualy/kotlogram#33]
sometime i receive this crash, i don't know why.

```
W/System.err: java.io.IOException: Reached end-of-stream
W/System.err:     at com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection.readBytes(MTProtoTcpConnection.kt:156)
W/System.err:     at com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection.readBytes$default(MTProtoTcpConnection.kt:147)
W/System.err:     at com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection.readMessage(MTProtoTcpConnection.kt:78)
W/System.err:     at com.github.badoualy.telegram.mtproto.MTProtoWatchdog.readMessage(MTProtoWatchdog.kt:94)
W/System.err:     at com.github.badoualy.telegram.mtproto.MTProtoWatchdog.access$readMessage(MTProtoWatchdog.kt:18)
W/System.err:     at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$run$2$1$1.run(MTProtoWatchdog.kt:56)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by badoualy** [comment]
Yes, this is an annoying issue, doesn't seem to be affecting other Telegram libs as far as I know (at least the devs I'm in contact with).
I'm guessing there must be something wrong with the mtproto implementation or the network layer but I have no clue, and since we have no Telegram support, I'm lost.

This is also why I implemented the "auto-reconnect" feature as a "hack" for this bug.

**Comment by xanscale** [comment]
on android when i receive this exception app crash.

i don't know why becaouse this is a managed exception and i don't see any unmanaged exception stack strace

**Comment by vishnyakov-aleks** [comment]
yet some logs
![alot4xmpp - -ideaprojects-alot4xmpp - alot4xmpp_main - -ideaprojects-alot4xmpp-src-main-java-ru-tro-alot4xmpp-singleton-echowatcher java - intellij idea 2017 2_051](https://user-images.githubusercontent.com/17671328/28880880-09588aea-77af-11e7-93d1-67e2426e680e.png)

**Comment by badoualy** [comment]
Attempt to fix with RC3, please update and tell if you still have the bug.

I removed the KEEP_ALIVE flag on the socket, which is not needed (and not used in official clients).

It the bug is still present, I'll attempt to add a Ping request every 1 min or so, to see if it has anything to do with inactivity.

**Comment by vishnyakov-aleks** [comment]
![_067](https://user-images.githubusercontent.com/17671328/29107704-21508a50-7ce4-11e7-94a4-e073585288d2.png)

And that connections are down and not reconnecting... but not all. i have pull of clients and at last night 3 of 5 crashed

**Comment by vishnyakov-aleks** [comment]
I forgot to say. It was RC3 version

**Comment by prassein** [comment]
I met the same issue today. After I changed DC5 to "@JvmField val PROD_DC5 = DataCenter("149.154.171.5", 443)", it works fine now.

**Comment by badoualy** [comment]
You probably had a different issue, DC5's ip seems to be changing quite often, probably you're in a geozone using this one, and that's why you had issue connecting :)
