### ISSUE TITLE
where to find auth.key and dc.save

### ISSUE THREAD

**Issue by nanangTriAndika** [badoualy/kotlogram#42]
Hii all,

I have some issue regarding auth.key, when I try to using key from App configuration, I got :

Exception in thread "main" java.lang.RuntimeException: AuthKey must be 256 Bytes found 425 bytes
	at com.github.badoualy.telegram.mtproto.auth.AuthKey.<init>(AuthKey.kt:14)
	at testelegram.ApiStorage.loadAuthKey(ApiStorage.java:33)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.<init>(DefaultTelegramClient.kt:54)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt:32)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient$default(Kotlogram.kt:31)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt)
	at testelegram.TesTelegram.main(TesTelegram.java:36)

Could someone share me example for auth.key and dc.save file ?

Thank you very much

**Comment by nanangTriAndika** [comment]
nevermind, I found the solution...

btw will give suggestion edit for get started section in your documentation, hope you liked it

**Comment by badoualy** [comment]
Hi, I'm currently doing a heavy refactoring (rewriting of the lib), the doc will be updated when I'm done accordingly, a lot will change :)

**Comment by nanangTriAndika** [comment]
@badoualy : Great... just tell me if you need some help
