### ISSUE TITLE
Error in callback or something

### ISSUE THREAD

**Issue by m-rain** [badoualy/kotlogram#7]
Hi
Kotlogram is awesome, Thank you for your work on it :)

When I call messagesGetMessagesViews method it work's successfully but I think after the response It shows an error and error again

Here is my log

> Exception in thread "RxComputationThreadPool-4" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: com.github.badoualy.telegram.tl.exception.DeserializationException: Unsupported constructor: #2
	at rx.Observable$26.onError(Observable.java:7954)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:188)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:85)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:202)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.lang.RuntimeException: com.github.badoualy.telegram.tl.exception.DeserializationException: Unsupported constructor: #2
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.onMessageReceived(MTProtoHandler.kt:354)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.access$onMessageReceived(MTProtoHandler.kt:29)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler$startWatchdog$2.call(MTProtoHandler.kt:93)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler$startWatchdog$2.call(MTProtoHandler.kt:29)
	at rx.Observable$11.onNext(Observable.java:4448)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
	... 12 more
Caused by: com.github.badoualy.telegram.tl.exception.DeserializationException: Unsupported constructor: #2
	at com.github.badoualy.telegram.tl.TLContext.deserializeMessage(TLContext.java:95)
	at com.github.badoualy.telegram.tl.TLContext.deserializeMessage(TLContext.java:69)
	at com.github.badoualy.telegram.tl.core.TLVector.deserializeItem(TLVector.java:87)
	at com.github.badoualy.telegram.tl.core.TLVector.deserializeBody(TLVector.java:82)
	at com.github.badoualy.telegram.tl.TLContext.deserializeMessage(TLContext.java:83)
	at com.github.badoualy.telegram.tl.TLContext.deserializeMessage(TLContext.java:69)
	at com.github.badoualy.telegram.tl.TLContext.deserializeMessage(TLContext.java:64)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.handleResult(MTProtoHandler.kt:480)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.handleMessage(MTProtoHandler.kt:380)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.onMessageReceived(MTProtoHandler.kt:346)
	... 17 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: [B.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:188)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
	... 12 more

**Comment by badoualy** [comment]
Do you get a correct response for messagesGetMessagesViews or is the error when receiving the response?

I don't even know what does the messagesGetMessagesViews method, since Telegram's documentation is outdated.

The error here is that you received a payload that the library can't deserialize

**Comment by m-rain** [comment]
No, actually I don't get the response and app hangs on this line

`client.messagesGetMessagesViews(ch, ids, true);`

**Comment by badoualy** [comment]
Ok, it means that the exception above is probably when deserializing the response, you can see the line
```
 at com.github.badoualy.telegram.mtproto.MTProtoHandler.handleResult(MTProtoHandler.kt:480)
```

This method is called when a response to a RPC method is received. I'll do some test when I have time, but as I said, I don't know what this method is suppose to do due to the lack of documentation on Telegram's side, and I don't need to use it, so sadly it's not a priority for me currently

**Comment by m-rain** [comment]
ok, thank you

**Comment by badoualy** [comment]
Related to #6 too

**Comment by badoualy** [comment]
Should be fixed with 
```gradle
compile 'com.github.badoualy:kotlogram:453951a73e'
```

Some methods were trying to deserialize int, long and string vectors as TLObject vectors
