### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by m-rain** [badoualy/kotlogram#8]
Hi

I tried to import a link hash. but when the link is expired the app stops.

I also tried to catch the errors but It stops again with this error: 

> MTProtoHandler# rpcError 400: INVITE_HASH_EXPIRED
com.github.badoualy.telegram.mtproto.exception.RpcErrorException: 400: INVITE_HASH_EXPIRED
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.handleResult(MTProtoHandler.kt:477)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.handleMessage(MTProtoHandler.kt:380)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.onMessageReceived(MTProtoHandler.kt:346)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.access$onMessageReceived(MTProtoHandler.kt:29)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler$startWatchdog$2.call(MTProtoHandler.kt:93)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler$startWatchdog$2.call(MTProtoHandler.kt:29)
	at rx.Observable$11.onNext(Observable.java:4448)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:85)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:202)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

It seems that error is happening in thread in library so I can't catch it
Do you know anyway to solve this?

**Comment by badoualy** [comment]
You should be able to catch the exception with
```java
try {
     client.importHash...
} catch (RpcErrorException e){

}
```

If that's not the case I'll check, the error handling in the library is not good for now, I plan to work on this in a few weeks

**Comment by m-rain** [comment]
When I add

`} catch (RpcErrorException e){

}`

It says the exception is never thrown

but when I add this line the "never thrown error" is disappearing

It looks like some methods are not handling RpcException, right?

I know a little in java but not kotlin, Would be glad to help you on this if you want

**Comment by badoualy** [comment]
So having the try/catch fixes the issue?
If yes, then nothing more to do, the issue about Kotlin is that the exceptions are not declared in the method prototype (see https://kotlinlang.org/docs/reference/exceptions.html for more info)
I'll check it when I have some time to force catching the RpcErrorException

**Comment by m-rain** [comment]
I mean import hash method is not throwing RcpException
but authSendCode throws RcpException

Thanks for your time :)

**Comment by badoualy** [comment]
All API methods now throws IO + RpcException.

Close if resolved, if not explain what's missing :)

**Comment by m-rain** [comment]
WOW
What a fast work :)

I'll check it out. closing the ticket for now

thanks again
