### ISSUE TITLE
Run Telegram again problem

### ISSUE THREAD

**Issue by m-rain** [badoualy/kotlogram#9]
Hi

When I try to make a new telegramClient after closing the last I got these errors

> java.util.concurrent.RejectedExecutionException: Task com.github.badoualy.telegram.mtproto.MTProtoWatchdog@4883b407 rejected from java.util.concurrent.ThreadPoolExecutor@7d9d1a19[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
	at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$start$1.call(MTProtoWatchdog.kt:113)
	at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$start$1.call(MTProtoWatchdog.kt:105)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.subscribe(Observable.java:8264)
	at rx.Observable.subscribe(Observable.java:8231)
	at rx.Observable.subscribe(Observable.java:7945)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.startWatchdog(MTProtoHandler.kt:96)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.init(DefaultTelegramClient.kt:60)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.<init>(DefaultTelegramClient.kt:53)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt:15)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient$default(Kotlogram.kt:14)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt)
	at com.github.badoualy.telegram.Main.main(Main.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Exception in thread "RxComputationThreadPool-1" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: Task com.github.badoualy.telegram.mtproto.MTProtoWatchdog@4883b407 rejected from java.util.concurrent.ThreadPoolExecutor@7d9d1a19[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at rx.Observable$26.onError(Observable.java:7954)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.util.concurrent.RejectedExecutionException: Task com.github.badoualy.telegram.mtproto.MTProtoWatchdog@4883b407 rejected from java.util.concurrent.ThreadPoolExecutor@7d9d1a19[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
	at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$start$1.call(MTProtoWatchdog.kt:113)
	at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$start$1.call(MTProtoWatchdog.kt:105)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.subscribe(Observable.java:8264)
	at rx.Observable.subscribe(Observable.java:8231)
	at rx.Observable.subscribe(Observable.java:7945)
	at com.github.badoualy.telegram.mtproto.MTProtoHandler.startWatchdog(MTProtoHandler.kt:96)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.init(DefaultTelegramClient.kt:60)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.<init>(DefaultTelegramClient.kt:53)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt:15)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient$default(Kotlogram.kt:14)
	at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt)
	at com.github.badoualy.telegram.Main.main(Main.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Here is my code:
`TelegramClient client;
client = Kotlogram.getDefaultClient(app, new ApiStorage());
Utils.print(Utils.isRegistered(client) + "");
client.close();
client = Kotlogram.getDefaultClient(app, new ApiStorage());
Utils.print(Utils.isRegistered(client) + "");
client.close();`

Error is happening in the second `client = Kotlogram.getDefaultClient(app, new ApiStorage());`
 
This problem does not exist in the 5 release. today after I updated to the newest version I faced this problem

**Comment by m-rain** [comment]
I found this if this helps

> There are two reasons why execute would throw a RejectedExecutionException

The queue is full and you cannot add any more threads
The ThreadPool has been shutdown

**Comment by badoualy** [comment]
If you close a client and plan to create another one in the applciation lifecycle, you need to use
```java
client.close(false);
```

The reason is that by default, when closing a client, it'll stop some threads, timer, etc used by the library or else your process would not terminate.

When you're done, you can call
```java
client.close(false);
Kotlogram.cleanUp();
```

equivalent of

```java
client.close();
```
